#!/usr/bin/env python3
"""Regenerate the acceptance-criteria index from the per-sprint breakdown files.

The index (docs/business/acceptance-criteria.md) is derived, never hand-edited.
Run this after any change to the sprint breakdown bodies so the index cannot
drift from them.

    python scripts/build_ac_index.py --business-dir docs/business --write

Without --write the generated index is printed to stdout for review.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

SPRINT_FILE_RE = re.compile(r"acceptance-criteria-sprint-(\d+)\.md$")
US_HEADING_RE = re.compile(r"^##\s+(US-\d+)\s+—\s+(.*?)\s*\(([^)]*)\)\s*$")
AC_HEADING_RE = re.compile(r"^###\s+(AC-\d+\.\d+)\s+—\s+(.*?)\s*$")
SPRINT_GOAL_RE = re.compile(r"^##\s+Sprint\s+(\d+)\s+—\s+(.*?)\s*$")
FOCUS_RE = re.compile(r"^\*\*Sprint focus:\*\*\s+(.*?)\s*$")


@dataclass
class Story:
    story_id: str
    title: str
    persona: str
    criteria: list = field(default_factory=list)

    @property
    def number(self) -> int:
        return int(self.story_id.split("-")[1])


@dataclass
class Sprint:
    number: int
    focus: str = ""
    stories: list = field(default_factory=list)

    @property
    def ac_count(self) -> int:
        return sum(len(s.criteria) for s in self.stories)


def parse_sprint_file(path: Path) -> Sprint:
    """Read one breakdown file, preserving every US and AC heading verbatim."""
    match = SPRINT_FILE_RE.search(path.name)
    if not match:
        raise ValueError("not a sprint breakdown file: %s" % path)
    sprint = Sprint(number=int(match.group(1)))
    current = None

    for line in path.read_text(encoding="utf-8").splitlines():
        if not sprint.focus:
            focus = FOCUS_RE.match(line)
            if focus:
                sprint.focus = focus.group(1)
                continue
        us = US_HEADING_RE.match(line)
        if us:
            current = Story(us.group(1), us.group(2), us.group(3))
            sprint.stories.append(current)
            continue
        ac = AC_HEADING_RE.match(line)
        if ac and current is not None:
            current.criteria.append((ac.group(1), ac.group(2)))

    return sprint


def read_sprint_goals(business_dir: Path) -> dict:
    """Pull sprint focus titles from sprint-breakdown.md when present."""
    path = business_dir / "sprint-breakdown.md"
    if not path.exists():
        return {}
    goals = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        match = SPRINT_GOAL_RE.match(line)
        if match:
            goals[int(match.group(1))] = match.group(2)
    return goals


def numbering_gaps(story_numbers: list) -> list:
    """Return inclusive ranges of story numbers missing from the sequence."""
    if not story_numbers:
        return []
    present = set(story_numbers)
    gaps = []
    start = None
    for n in range(min(story_numbers), max(story_numbers) + 1):
        if n in present:
            if start is not None:
                gaps.append((start, n - 1))
                start = None
        elif start is None:
            start = n
    if start is not None:
        gaps.append((start, max(story_numbers)))
    return gaps


def format_gap(low: int, high: int) -> str:
    if low == high:
        return "US-%02d" % low
    return "US-%02d to US-%02d" % (low, high)


def render(sprints: list, goals: dict) -> str:
    total_stories = sum(len(s.stories) for s in sprints)
    total_ac = sum(s.ac_count for s in sprints)
    all_numbers = sorted(st.number for s in sprints for st in s.stories)
    gaps = numbering_gaps(all_numbers)

    out = []
    out.append("# Archiva Acceptance Criteria Index")
    out.append("")
    out.append("**Version:** 1.0  ")
    out.append("**Date:** %s  " % date.today().isoformat())
    out.append("**Status:** Generated  ")
    out.append("**Generator:** `scripts/build_ac_index.py`  ")
    out.append("")
    out.append(
        "Do not edit this file by hand. Regenerate it after any change to "
        "`acceptance-criteria-breakdown/`:"
    )
    out.append("")
    out.append("```bash")
    out.append("python scripts/build_ac_index.py --business-dir docs/business --write")
    out.append("```")
    out.append("")

    for low, high in gaps:
        out.append(
            "> Note: %s absent from the scheduled sprints. "
            "Held as roadmap in `docs/us-ac/User-Stories-and-AC.md`."
            % format_gap(low, high)
        )
    if gaps:
        out.append("")

    out.append("## Sprints at a Glance")
    out.append("")
    out.append("| Sprint | Focus | User Stories | Acceptance Criteria |")
    out.append("| --- | --- | --- | --- |")
    for sprint in sprints:
        focus = goals.get(sprint.number) or sprint.focus or "(not set)"
        out.append(
            "| Sprint %d | %s | %d | %d |"
            % (sprint.number, focus, len(sprint.stories), sprint.ac_count)
        )
    out.append("| **Total** | | **%d** | **%d** |" % (total_stories, total_ac))
    out.append("")

    for sprint in sprints:
        focus = goals.get(sprint.number) or sprint.focus or "(not set)"
        out.append("---")
        out.append("")
        out.append("## Sprint %d — %s" % (sprint.number, focus))
        out.append("")
        out.append(
            "Full scenario bodies: "
            "`acceptance-criteria-breakdown/acceptance-criteria-sprint-%d.md`"
            % sprint.number
        )
        out.append("")
        for story in sprint.stories:
            out.append(
                "### %s — %s (%s)" % (story.story_id, story.title, story.persona)
            )
            out.append("")
            for ac_id, scenario in story.criteria:
                out.append("- %s — %s" % (ac_id, scenario))
            if not story.criteria:
                out.append("- (no acceptance criteria defined)")
            out.append("")

    return "\n".join(out).rstrip() + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--business-dir",
        default="docs/business",
        type=Path,
        help="directory holding sprint-breakdown.md and acceptance-criteria-breakdown/",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="write acceptance-criteria.md instead of printing to stdout",
    )
    args = parser.parse_args(argv)

    business_dir = args.business_dir
    breakdown_dir = business_dir / "acceptance-criteria-breakdown"
    if not breakdown_dir.is_dir():
        print("error: no breakdown directory at %s" % breakdown_dir, file=sys.stderr)
        return 1

    files = sorted(
        (p for p in breakdown_dir.glob("*.md") if SPRINT_FILE_RE.search(p.name)),
        key=lambda p: int(SPRINT_FILE_RE.search(p.name).group(1)),
    )
    if not files:
        print("error: no sprint files found in %s" % breakdown_dir, file=sys.stderr)
        return 1

    sprints = [parse_sprint_file(p) for p in files]
    content = render(sprints, read_sprint_goals(business_dir))

    if args.write:
        target = business_dir / "acceptance-criteria.md"
        target.write_text(content, encoding="utf-8")
        stories = sum(len(s.stories) for s in sprints)
        criteria = sum(s.ac_count for s in sprints)
        print(
            "wrote %s: %d sprints, %d stories, %d acceptance criteria"
            % (target, len(sprints), stories, criteria)
        )
    else:
        print(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
